name: Code Checker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Code Quality: Flake8
        uses: py-actions/flake8@v1.0.1
        with:
          path: goshort

      - name: Check Code Quality: Isort/Black
        uses: wrboyce/python-lint-action@v1.0.0
